var fragment = document.createDocumentFragment();
var jqScript = document.createElement("script");
jqScript.type = "text/javascript";
jqScript.src = "_ja-srs-utils.jquery-3.1.1.slim.min.js";
var cardScript = document.createElement("script");
cardScript.type = "text/javascript";
cardScript.src = "_ja-srs-utils.card.js";
var cardStyle = document.createElement("link");
cardStyle.rel = "stylesheet";
cardStyle.href = "_ja-srs-utils.card.css";
fragment.appendChild(jqScript);
fragment.appendChild(cardScript);
fragment.appendChild(cardStyle);
